# Generated by Django 3.1.2 on 2020-11-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images'),
        ),
    ]
