# Generated by Django 3.1.2 on 2020-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201109_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='title'),
            preserve_default=False,
        ),
    ]
