# Generated by Django 3.1.2 on 2020-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
