# Generated by Django 3.1.2 on 2020-11-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_userbook_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='slug',
        ),
    ]
